### PR TITLE
Add trackwidth conversions

### LINKED ISSUE #166: Track-width computation doesn't account for wheel circumference
In data_analyzer.py, calcTrackWidth returns the track width in units of wheel revolutions, not the project unit, as can be seen by considering that d_left and d_right are directly computed from table entries that are measured in revolutions in the self.stored_data table.
I noticed this in characterizing a Romi where the calculated track width was about 0.67m. For a more usual robot the scale of the error would be about a factor of 2 (too large, as 6" wheels have about a 0.5m circumference). I wonder if this behind the remark in https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/robot-characterization/characterization-routine.html that  "the empirical trackwidth calculated by frc-characterization may be significantly different from the real trackwidth (e.g., off by a factor of 2)."?

### PR DESCRIPTION
**Pull request by Piphi5**
Still need trackwidth characterization to verify this works.

Should close #166

### CODE REVIEW

**Comment by sciencewhiz** [comment]
Running characterization with the drivetrain simulation example (https://www.chiefdelphi.com/t/infinite-recharge-at-home-autonav-challenges-using-wpilibs-drive-simulator/390485) I had previously had a very large trackwidth (~64 meters) when it should be 0.69 meters. With this change, I now get 15.34 meters.

**Comment by Piphi5** [comment]
Did you log with meters as well?

**Comment by sciencewhiz** [comment]
I implemented the logger code into my project where the encoders returned meters. When I ran the logger, it said verify the robot traveled x rotations which was correct if substituting meters (it traveled x meters).

**Comment by Piphi5** [comment]
Did you set the units to meters in the new project section?

**Comment by sciencewhiz** [comment]
I did chose meters and put my units per rotation in the new project section. However, I just noticed that the generated project did not seem to use that. It generated `private double encoderConstant = (1 / GEARING) * (1 / ENCODER_EDGES_PER_REV);` and `encoder.setDistancePerPulse(encoderConstant);` which looks like it was using rotations regardless of the fact that I entered meters and and my meters per rotation. This would be different then my own project that I ran characterization on which returned encoder distances in meters

**Comment by Piphi5** [comment]
That might be another issue with the tool's units then...

**Comment by sciencewhiz** [comment]
After realizing that the robot program is always generated as rotations, and conversions to units are done in frc-characterization, I updated my robot program to report distance in rotations. My robot program was also limiting the gyro angle to -180/+180. Once I reported the accumulated gyro angle, with this PR, it reported the correct trackwidth for me.

**Comment by Piphi5** [comment]
Did you have to do the conversions in the analyzer or through the logger?

**Comment by sciencewhiz** [comment]
Previously, when I ran the logger and analyzer separately from the cli is when I had the issue with the logger reporting rotations. If instead I ran `frc-characterization drive new` and set the conversions in the main window and launched the logger and analyzer from there, the unit conversions worked.

**Comment by Piphi5** [comment]
So we should be able to resolve the issue through better documentation?

Also, were you able to see if switching the units to feet, inches, etc. were accurate?

**Comment by sciencewhiz** [comment]
The combination of this PR and better documentation would fix it. 

Yes, when switching between meters, feet, and inches, the trackwidth scaled appropriately.

**Comment by Piphi5** [comment]
> The combination of this PR and better documentation would fix it.
Would [this](https://github.com/wpilibsuite/frc-docs/pull/1148) PR make it clear?

**Comment by Piphi5** [comment]
Should close #166

**Review by sciencewhiz — APPROVED** [review]

**Review by calcmogul — APPROVED** [review]

**Pull request merged**
