### PR TITLE
Rename master/slave->leader/follower

### LINKED ISSUE #127: Should use Leader/Follower terminology, rather then Master/Slave

### PR DESCRIPTION
**Pull request by Starlight220**
Fixes #127

### CODE REVIEW

**Comment by Piphi5** [comment]
If I'm not mistaken, I believe there are also some master and slave terminology in the code for the analyzer.

**Comment by AustinShalit** [comment]
Does this handle loading projects with the old terminology?

**Comment by Piphi5** [comment]
> Does this handle loading projects with the old terminology?

Are you referencing old config files?

**Comment by calcmogul** [comment]
He's asking if old projects will continue to work after this change.

**Comment by calcmogul** [comment]
Looks like you forgot to rename "master" to "leader".

**Comment by Starlight220** [comment]
I didn't forget, I just didn't do it yet. Are we sure that we want to rename master->leader, as CTRE uses master/follower naming?

**Comment by Piphi5** [comment]
I think that should be good.

**Comment by calcmogul** [comment]
> And is there a reason that existing projects wouldn't work?

We don't know. That's why we're asking you. :)

**Comment by Starlight220** [comment]
For now, the only difference is variable naming in the generated code, so I see no reason it wouldn't be backward-compatible. Though I haven't looked too much at the internals, so IDK.

**Comment by Starlight220** [comment]
As of now (fa2d0ab), the templates are entirely in leader/follower terminology. Up to here the application is backward-compatible, as all integrations with the python analysis code are through `NetworkTableEntry` objects that haven't been renamed (nor is there a reason to rename them).

Should I continue to convert the application code itself (a change that might not be backward-compatible) or do you want to merge this first? If you merge this, the issue should be reopened or unlinked.

**Comment by Piphi5** [comment]
> As of now ([fa2d0ab](https://github.com/wpilibsuite/frc-characterization/commit/fa2d0abed3b36e79356df9fa8ddfda1c54806372)), the templates are entirely in leader/follower terminology. Up to here the application is backward-compatible, as all integrations with the python analysis code are through `NetworkTableEntry` objects that haven't been renamed (nor is there a reason to rename them).
> 
> Should I continue to convert the application code itself (a change that might not be backward-compatible) or do you want to merge this first? If you merge this, the issue should be reopened or unlinked.

I think you should update the analyzer as the primary goal of the issue is to make the naming more familiar to the user. Only changing internal variables doesn't really help with that.

**Comment by Starlight220** [comment]
It's a step. However, this application has (at least) three components that should switch terminology, each with their own risk of backward-incompatibility: the generated code (fixed in the current state of this PR), the project generator (that can also be split into frontend and the code itself), and the analyzer (this is the most important backward-compatibility-wise). I am asking the maintainers as to what extent should these changes be decoupled.
I think that the application code is the last that should be converted as it has absolutely no user interaction and most sensitive to changes and backward-compatibility. The templates are the least sensitive and have minimal risk of backward-incompatibility, therefore I converted them first. I'll look over the codebase to see what exactly can be converted with minimal risk, and convert it next (possibly in a separate PR).
I suggest decoupling these changes as they have different levels of risk, needed depth/focus of reviewing, and likeliness of being reverted/problematic.

**Comment by Piphi5** [comment]
> I suggest decoupling these changes as they have different levels of risk, needed depth/focus of reviewing, and likeliness of being reverted/problematic.

From my experience, the slave/master terms are either internal variables or labels for the UI. As long as you keep the variables consistent, there shouldn't be any risk of backward-incompatibility. Also, you can easily verify this by running a `pip install .` in the directory and making sure the template generation doesn't fail and that the analyzer can read old jsons.

**Comment by pietroglyph** [comment]
There's some discussion here on what's backwards compatible and what isn't, and I want to clarify that variable name changes and UI terminology changes are both backwards compatible. The only interface that has any serious compatibility considerations is the JSON format that goes to the analyzer, which is not affected here (it does not use master/slave terminology.)

**Comment by Starlight220** [comment]
I'm done with this, feel free to review.

**Comment by PeterJohnson** [comment]
Needs conflicts fixed, but otherwise looks good.

**Comment by sciencewhiz** [comment]
How bad will this conflict with #126? Does it make sense to do one before the other?

**Comment by Piphi5** [comment]
> How bad will this conflict with #126? Does it make sense to do one before the other?

It shouldn't conflict too badly with #126 as it also makes these changes. From my experience updating #126 locally, the worst that could happen is that all these changes are overwritten/deleted. 

As for the second question, I'm not too sure what would be the best course of action.

**Comment by Starlight220** [comment]
@sciencewhiz @Piphi5 -  I believe that 126 does too many things that it should be broken into multiple smaller, focused PRs. If wanted I can help with that.

**Comment by calcmogul** [comment]
#126 fixed this.

**Pull request closed without merging**
