### PR TITLE
Comments Pertaining to Falcon500, Wording in robot.java

### PR DESCRIPTION
**Pull request by jabbate19**
Working on this for my Falcon500 powered gearbox, I was getting confused due to the differences between the Falcon500 motor and the other encoders within robotics. The Falcon500 is not a quadrature encoder, so its CPR = its EPR. Due to this, if you put the value of 2048 into the software for EPR, the code would end up dividing it by 4, causing an bug when running the program. I added a comment into the config that will tell the user what value to use for the Falcon 500s. Also, while looking into robot.java, I realized that a variable that to my knowledge is holding the value of the CPR was named EPR, so I changed the name of it as well.

This is my first time putting in a PR to a public Repo, so please let me know if theres anything I can change to improve this!

Joe A, Programmer for FRC 4567

### CODE REVIEW

**Comment by Piphi5** [comment]
You should rebase instead of merging.

**Comment by jabbate19** [comment]
I don't know what that means or how to do it. What would I need to do?

> You should rebase instead of merging.

**Comment by calcmogul** [comment]
With your feature branch checked out, you do `git rebase master` instead of `git merge master`'.

**Comment by sciencewhiz** [comment]
This was superseded by #180, right?

**Comment by calcmogul** [comment]
Looks like it has been.

**Pull request closed without merging**
