### PR TITLE
Factory Reset all CAN motor controllers

### LINKED ISSUE #61: Add factory reset to NEO project
The Spark MAX's exhibited weird behavior (not inverting at all, regardless of true or false) along with odd follower behavior before calling factory reset on them.

### PR DESCRIPTION
**Pull request by Starlight220**
Closes #61 
- [x] Drive - brushed
- [x] Drive - brushless
- [x] arm - brushed
- [x] arm - brushless
- [x] elevator - brushed
- [x] elevator - brushless
- [x] simplemotor - brushed
- [x] simplemotor - brushless

### CODE REVIEW

**Comment by Starlight220** [comment]
Can someone with write access link this to 61? The keyword linking doesn't work for some reason.
Also, why is the CI failing on files that I haven't touched?

**Comment by Piphi5** [comment]
> Can someone with write access please link this to 61? The keyword linking doesn't work for some reason.
> Also, why is the CI failing on files that I haven't touched?

The black formatted had an update so some of the current code fails.

**Comment by Piphi5** [comment]
Also, #126 unifies the templates so I'd recommend adding your changes onto there instead of a separate PR.

**Comment by Starlight220** [comment]
As others have already pointed out, 126 does too many things and should be split into multiple smaller PRs.

**Comment by Piphi5** [comment]
Should factory resets for Talons also be added?

**Comment by Starlight220** [comment]
Yes, now adding it.

**Comment by calcmogul** [comment]
OBE by #126.

**Pull request closed without merging**
