### PR TITLE
Improve Config Setup

### PR DESCRIPTION
**Pull request by Piphi5**
Got rid of controlType in the config files and separated configs into 3
different files depending on the type of motor controllers used (CTRE,
SparkMax, and Simple). This should remove unnecessary parameters for each
different type of config.

Made it so declaring encoder ports for smart motor controllers
(e.g. Spark Max and Talon SRX) makes the template use Encoders from the
RoboRIO rather than the motor controller.

Removed the need to declare the CANSparkMax motor controller type when
working with the SparkMax control type under the assumption that the
vast majority of uses will not require mixing SparkMaxes with other
motor controller types.

Also clarified config file documentation.

I need to do some extra testing to make sure nothing breaks, but this should be the bulk of the changes.

### CODE REVIEW

**Comment by calcmogul** [comment]
Is there a way we could generate projects in CI to make sure the templates compile?

**Comment by Piphi5** [comment]
There's no straightforward solution that I know off the top of my head since the generation is done through the UI. This might be something we should abstract with the math analysis when creating Unit Tests and test cases.

**Comment by pietroglyph** [comment]
> Is there a way we could generate projects in CI to make sure the templates compile? It would have caught the bug the most recent fixup commit addressed.

Yeah, that's definitely doable. We might have to factor the generation code into some more independent functions, but it should be quite straightforward (and could probably fit into a doctest.) That, plus some doctests for data loading and processing, would go a long way for reliability and dev effort. I don't think it's a ton of work beyond refactoring some of the code into more standalone functions.

**Comment by Piphi5** [comment]
Should this PR handle that?

**Comment by pietroglyph** [comment]
No, I don't think that's in the scope of polishing the project generator config.

**Comment by calcmogul** [comment]
In the meantime, we need someone to test this PR for correctness.

**Comment by Piphi5** [comment]
Would the following test cases be good (the different encoder types for the SparkMax cases are each separate cases)?

- [ ] Simple 2 motorcontroller config
- [ ] Simple 2 motorcontroller per-side drive 
- [ ] CTRE Talon, Victor setup w and w/o Rio-side encoder
- [ ] CTRE Talon, Victor setup per-side drive w and w/o Rio-side encoder
- [ ] SparkMax 2 NEO setup with Integrated, External, and Rio Side encoders
- [ ] SparkMax 2 Brushed Motor setup with External and Rio Side encoder
- [ ] SparkMax 2 NEO per-side, drive setup with Integrated Encoder and External encoders
- [ ] SparkMax 2 Brushed Motor per-side drive setup with External and Rio Side Encoder

**Comment by calcmogul** [comment]
What's a `CTRE Talon, Victor setup per-side drive`?

**Comment by Piphi5** [comment]
> What's a `CTRE Talon, Victor setup per-side drive`?

A drivetrain config that uses a Talon with a Victor follower setup on each side.

**Comment by calcmogul** [comment]
Then what's the difference between `CTRE Talon, Victor setup w and w/o Rio-side encoder` and `CTRE Talon, Victor setup per-side drive w and w/o Rio-side encoder`? Maybe you should just use complete sentences, because I'm really confused.

**Comment by Piphi5** [comment]
> Then what's the difference between `CTRE Talon, Victor setup w and w/o Rio-side encoder` and 

That one is just a simple-motor setup.

> `CTRE Talon, Victor setup per-side drive w and w/o Rio-side encoder`?

This one is a drivetrain setup.

Would `A drivetrain setup using a Talon with a Victor follower on each side with and without a Rio-side encoder` vs `A simple motor setup using a Talon with a Victor Follower with and without a Rio-side encoder`  make the test cases clearer?

**Comment by calcmogul** [comment]
That's much clearer, yeah.

**Comment by Piphi5** [comment]
> Would the following test cases be good (the different encoder types for the SparkMax cases are each separate cases)?
> 
> * [ ]  A simple motor setup with 2 simple motorcontrollers (e.g. Spark)
> * [ ]  A drivetrain setup with 2 simple motorcontrollers on each side
> * [ ]  A simple motor setup using a Talon with a Victor Follower with and without a Rio-side encoder
> * [ ]  A drivetrain setup using a Talon with a Victor follower on each side with and without a Rio-side encoder
> * [ ]  A simple motor setup with 2 NEOs using Integrated, External, and Rio Side encoders
> * [ ]  A simple motor setup with 2 Brushed SparkMax motorcontrollers using External and Rio Side encoders
> * [ ]  A drivetrain with 2 NEOs on each side using Integrated encoders, External encoders, and Rio Side encoders
> * [ ]  A drivetrain with 2 Brushed SparkMax motorcontrollers on each side using External and Rio Side Encoders

Are these test cases clearer?

**Comment by calcmogul** [comment]
That list looks good so far. Do we want to do anything in particular involving the gyro?

**Comment by Piphi5** [comment]
I can use the NavX and Pigeon for all of the drivetrain cases

**Comment by calcmogul** [comment]
Does that cover a CCW positive gyro and a CW positive one? I don't know what coordinate systems those use.

**Comment by Piphi5** [comment]
> Does that cover a CCW positive gyro and a CW positive one? I don't know what coordinate systems those use.

I believe the NavX is CW positive and the Pigeon is CCW positive.
Is there anything I should be looking out for in terms of the generated code relating to the orientation?

**Comment by calcmogul** [comment]
Yea. If it's a CW positive gyro, we have to throw on a negative sign to make it CCW positive.

**Comment by calcmogul** [comment]
Hopefully once vendors implement GetRotation2d() correctly, we can just use that.

**Comment by Piphi5** [comment]
I assume AnalogGyro is CCW Positive?

**Comment by calcmogul** [comment]
Oh, and we could use the simulation physics to verify the stats stuff gives the right Kv and Ka.

**Comment by Piphi5** [comment]
> Oh, and we could use WPILib's simulation physics to verify the stats stuff gives the right Kv and Ka.

Would this serve as an additional check to the LQR Unit Tests?

**Comment by calcmogul** [comment]
> Would this serve as an additional check to the LQR Unit Tests?

The feedforward gains and feedback gains should be tested separately.

**Comment by calcmogul** [comment]
> I assume AnalogGyro is CCW Positive?

The analog gyro 3512 used in 2013 was CW positive, but it really depends on the gyro you plug into the analog input pin.

**Comment by Piphi5** [comment]
>  but it really depends on the gyro you plug into the analog input pin.
Should that be another template field, or should we ask the users in the documentation to flip the sign on the template if the analog gyro isn't CCW positive?

**Comment by calcmogul** [comment]
So few teams use analog gyros nowadays that I'd rather just document it.

**Comment by Piphi5** [comment]
It handles all the test cases now, but could somebody look at the 3 new config files and see if they are understandable?

**Review by calcmogul — APPROVED** [review]

**Pull request merged**
