### PR TITLE
Use json.loads() for config loading instead of ast.literal_eval()

### PR DESCRIPTION
**Pull request by calcmogul**
Use json.loads() for config loading instead of ast.literal_eval()

This will give better error messages when the config is malformed.

The config was already in JSON format, so all that was required is first
stripping out comments, because those aren't allowed in fully compliant
JSON.

### CODE REVIEW

**Comment by pietroglyph** [comment]
I don't think the current configs are valid JSON? They have Python-style bool literals (e.g. `True` and `False`.)

**Comment by calcmogul** [comment]
How about now? :slightly_smiling_face:

**Comment by calcmogul** [comment]
The default config crashes on a "list index out of range" error on both master and this patch. I've at least verified the JSON parser doesn't throw an error on it.

**Comment by Oblarg** [comment]
If we had JSON config files, I'd be fine with this, but the config files are python literals.

**Comment by calcmogul** [comment]
This PR converts them to valid JSON in a backwards-compatible way. However, if the compile-eval PR make the syntax errors readable, then I'm fine with closing this PR.

**Pull request closed without merging**
