### PR TITLE
Multithreading Code Deploy

### PR DESCRIPTION
**Pull request by Piphi5**
Moved the action of the code deploy to a separate background worker
thread that updates the GUI through a process queue function every 10
ms. This helps the deploy process not freeze the application whenever
deploying.

### CODE REVIEW

**Review by pietroglyph — APPROVED** [review]
Makes sense to me.

**Comment by calcmogul** [comment]
Only thing left is for someone to test it irl. :slightly_smiling_face:

**Comment by Piphi5** [comment]
The deploy worked when I tested it.

**Comment by Piphi5** [comment]
The code deployed fine on a roborio testbed and the UI window didn't freeze. Is there anything else I should test?

**Review by calcmogul — APPROVED** [review]

**Pull request merged**
