### PR TITLE
Add gyro measurement for trackwidth

### LINKED ISSUE #170: Add gyro rotations to logger display when doing track width characterization
When doing trackwidth characterization, the logger window shows you how many (units) the left and right wheels rotated. However, when the robot is spinning in circles this isn't an intuitive number. Recommend adding the degrees of rotation from the gyro, which someone could verify.

### PR DESCRIPTION
**Pull request by Piphi5**
Supposed to close #170.

Hasn't been tested yet.

### CODE REVIEW

**Comment by sciencewhiz** [comment]
It should call out that the units are Radians (or convert to degrees, which is likely to be more approachable). Other then that, it worked.
image

**Comment by Piphi5** [comment]
@sciencewhiz 

Can you verify if the latest commit properly converts the measurement?

**Comment by sciencewhiz** [comment]
The conversion seems reasonable, but it's a little less then what the simulated gyro reports. 
image

**Comment by Piphi5** [comment]
Could that be from the robot still turning a little bit after its disabled?

**Comment by sciencewhiz** [comment]
It's certainly possible

**Comment by sciencewhiz** [comment]
To avoid merge conflicts, it would probably easier if you incorporated #171 in this PR

**Comment by Piphi5** [comment]
> To avoid merge conflicts, it would probably easier if you incorporated #171 in this PR

Does the latest commit cover these changes?

**Comment by sciencewhiz** [comment]
yep

**Review by sciencewhiz — APPROVED** [review]

**Review by calcmogul — APPROVED** [review]

**Pull request merged**
