### PR TITLE
Update PWF library json and rename pwfconfig.py

### PR DESCRIPTION
**Pull request by CodingWithFusion**
Updated to latest version of PWF vendor libraries (playingwithfusion2021.json) which now include Linux and OSX simulation libraries

Renamed pwfconfig.py to venomconfig.py.   This bug was introduced when I changed the configuration in the frc-characterisation GUI from 'PWF' to 'Venom'

Verified libPlayingWithFusion and frc-characterisation changes on robot and in Win32 simulation.

### CODE REVIEW

**Comment by CodingWithFusion** [comment]
Hi @calcmogul, There's a competition in Quebec starting on Thursday and I'd like them to have this change.   If you're not planning a release this week, is there an easy way to distribute python libraries locally?   There are only 10 teams involved, so it's not the end of the world to touch each machine manually.

I'm not a python guru.  I found where PIP saves the packages locally and can share my library build as a zip file, along with instructions to integrate them.    Is their an easier/better way?

**Review by calcmogul — APPROVED** [review]

**Comment by pietroglyph** [comment]
Pip can install from any Git repo: https://stackoverflow.com/a/20101940

You can have them install from the main branch of this repo.

**Comment by CodingWithFusion** [comment]
Sounds great, thanks

**Comment by Piphi5** [comment]
@CodingWithFusion 
I have added some C++ Code to the [new tool](https://github.com/wpilibsuite/sysid/pull/138).

Let me know if you have any suggestions for this implementation.

**Comment by CodingWithFusion** [comment]
Thanks!   Looks good so far

**Pull request merged**
